services:

  sgcc-alert-build:
    build:
      context: .
      target: dev
    image: sgcc-alert:${IMAGE_TAG:-latest}

  sgcc-alert-run:
    image: sgcc-alert:${IMAGE_TAG:-latest}
    depends_on:
      - sgcc-alert-homeassistant
    volumes:
      - ./:/app/sgcc-alert/
    command: ["python", "-m", "sgcc_alert.app"]

  sgcc-alert-homeassistant:
    image: homeassistant/home-assistant:stable
    restart: unless-stopped
    ports:
      - "30001:8123"
