
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

automation sgcc:
  - alias: "Update resident options"
    triggers:
      - trigger: event
        event_type: homeassistant.start
      - trigger: time_pattern
        minutes: "/5"
    actions:
      - action: rest_command.get_residents
        response_variable: get_residents_response
      - delay: "00:00:05"
      - action: input_select.set_options
        target:
          entity_id: input_select.sgcc_resident
        data:
          options: >
            {%- set ns = namespace(options=[]) -%}
            {%- for item in get_residents_response['content']['data'] -%}
              {%- set ns.options = ns.options + [[item['resident_address'], item['resident_id'], ( '主户' if item['is_main'] else '非主户' )] | join(' | ')] -%}
            {% endfor %}
            {{ ns.options }}

  - alias: "Update SGCC API on Resident Option Changing"
    trigger:
      - platform: state
        entity_id: input_select.sgcc_resident
    action:
      - service: homeassistant.update_entity
        target:
          entity_id: sensor.sgcc_resident_latest_balance

rest_command:
  get_residents:
    url: 'http://sgcc-alert:8000/api/v1.0/residents'
    method: 'GET'
    headers:
      Content-Type: 'application/json'

input_select:
  sgcc_resident:
    name: "SGCC Residents"
    options:
      - "Loading..."

sensor:
  - platform: rest
    name: SGCC Resident Latest Balance
    unique_id: sgcc_resident_latest_balance
    resource_template: >
      {%- set select_option = states('input_select.sgcc_resident') -%}
      {%- set items = select_option.split(' | ') -%}
      {%- set ns = namespace(resident_id='') -%}
      {%- if items | length == 3 -%}
          {%- set _, resident_id, _ = items -%}
          {%- set ns.resident_id = resident_id -%}
      {% endif %}
      http://sgcc-alert:8000/api/v1.0/residents/{{ ns.resident_id }}/balances?order_by=date&order=desc&limit=1
    method: GET
    params:
      resident_id: >
        {%- set select_option = states('input_select.sgcc_resident') -%}
        {%- set items = select_option.split(' | ') -%}
        {%- if items | length != 3 -%}
            {{ '' }}
        {% else %}
            {%- set _, resident_id, _ = items -%}
            {{ resident_id }}
        {% endif %}
    value_template: >
      {%- set select_option = states('input_select.sgcc_resident') -%}
      {%- set items = select_option.split(' | ') -%}
      {%- if items | length != 3 -%}
          {{ 0 }}
      {% else %}
          {{ value_json.data[0].balance }}
      {% endif %}
    json_attributes_path: "$.data[0]"
    json_attributes:
      - resident_id
      - date
      - balance
    scan_interval: 3600
    device_class: monetary
    state_class: total
    unit_of_measurement: "CNY"
